name: Test generator request
description: Request used to define the requirements needed to create the tests template.
title: "[TEST] <title>"
labels: ["Test", "Template"]
body:
- type: input 
  attributes:
    label: Test Framework
    description: Select the Test Framework of your preference.
  validations:
    required: true
- type: input
  attributes:
    label: Common Feature
    description: Enter the feature to test.
  validations:
    required: true
