name: Test generator request
description: Request used to define the requirements needed to create the tests template.
title: "[TEST] <title>"
labels: ["Test", "Template"]
body:
- type: textarea
  attributes:
    label: Branch name
    description: Name of the branch that will be created on request approval.
  validations:
    required: true
- type: textarea
  attributes:
    label: Prompt
    description: GPT Prompt.
  validations:
    required: true
- type: textarea
  attributes:
    label: File Location
    description: Location of the tests created.
  validations:
    required: true
